enter_accept = false
keymap_mode = "auto"
search_mode = "daemon-fuzzy"

[stats]
common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "dnf",
  "docker",
  "git",
  "go",
  "ip",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",
  "mise",
  "pnpx",
  "bun",
  "bunx",
  "eas"
]

[keys]

[sync]
records = true

[preview]

[daemon]
enabled = true
autostart = true

[ui]
columns = ["time", "directory", "command"]

[ai]
enabled = true
