[".hammerspoon/Spoons/ControlEscape.spoon"]
type = "git-repo"
url = "https://github.com/jasonrudolph/ControlEscape.spoon"
refreshPeriod = "168h"

[".tmux"]
type = "git-repo"
url = "https://github.com/gpakosz/.tmux.git"
refreshPeriod = "168h"
