#!/bin/bash

# General
alias v='$EDITOR'

# Impatient.nvim
alias nvim="nvim --startuptime /tmp/nvim-startuptime"

# Tmux
function t() {
	local sessions
	local session

	if ! tmux has-session; then
		tmux new-session -s "dots"
	else
		sessions=$(tmux list-sessions -F \#S)
		session=$(echo "${sessions}" | gum filter --placeholder "Pick session...")
		tmux switch-client -t "${session}" || tmux attach -t "${session}"
	fi
}

alias tl="tmux ls"
alias ta="tmux a"

alias cm="chezmoi"

# Dotfiles
alias dots="chezmoi edit; chezmoi apply"

# Listing files
alias ls="exa --icons --color=always --classify --git --group-directories-first"
alias l="ls --git-ignore"
alias ll="ls --long"
alias la="ll -a"
alias tree="ll --tree --level=3"

alias dev="mprocs"

# Git
alias lg="lazygit"
alias gitroot="git rev-parse --show-toplevel"
alias cdr='cd $(gitroot)'

# Socialbrothers
function sb() {
	local sbdir=~/Code/Socialbrothers/
	if (($# != 0)); then
		z "$sbdir" "$@"
	else
		local dir
		dir=$(find "$sbdir"/* -maxdepth 0 -type d -exec basename {} \; | fzf-tmux --height 40% --reverse --border --preview="exa $sbdir/{} --icons --color=always -1 --classify --git --group-directories-first")
		cd "$sbdir$dir"
	fi

	local parent=$(dirname "$PWD")
	if [ "$OLDPWD" != "$PWD" ] && [ "$parent" -ef "$sbdir" ]; then
		local dirname
		dirname=$(basename "$PWD" | sed 's/-\|_/ /g' | sed '/\b(\S)/g')
		figlet -f "big" -w 9999 "$dirname" | cut -c -"$COLUMNS" | lolcat
	fi
}

function adbw() {
	wifion=$(adb shell settings get global wifi_on)
	if [[ ${wifion} == 1 ]]; then
		adb shell svc wifi disable
	else
		adb shell svc wifi enable
	fi
}

lfcd() {
	tmp="$(mktemp)"
	lf -last-dir-path="$tmp" "$@"
	if [ -f "$tmp" ]; then
		dir="$(cat "$tmp")"
		rm -f "$tmp"
		if [ -d "$dir" ]; then
			if [ "$dir" != "$PWD" ]; then
				cd "$dir"
			fi
		fi
	fi
}
