#!/bin/bash

__wezterm_set_user_var() {
    if hash base64 2>/dev/null; then
        based="$(echo -n "$2" | base64)"
        printf "\033]1337;SetUserVar=%s=%s\007" "$1" "${based}"
    fi
}

function _run_prog() {
    # set PROG to the program being run
    __wezterm_set_user_var "PROG" "$1"

    # arrange to clear it when it is done
    trap '__wezterm_set_user_var PROG ""' EXIT

    # and now run the corresponding command, taking care to avoid looping
    # with the alias definition
    command "$@"
}

alias nvim="_run_prog nvim"

# General
alias v='$EDITOR'

function upgrade() {
    true
}

alias cm="chezmoi"

# Dotfiles
alias dots="chezmoi edit --watch --apply"

# Listing files
alias ls="exa --icons --color=always --classify --git --group-directories-first"
alias l="ls --git-ignore"
alias ll="ls --long"
alias la="ll -a"
alias tree="ll --tree --level=3"

alias dev="mprocs"

alias tlr="taze latest --recursive"
alias tlri="taze latest --recursive --write --install"

# Git
alias lg="lazygit"
alias gitroot="git rev-parse --show-toplevel"
alias cdr='cd $(gitroot)'

# Tmux
function t() {
    local sessions
    local session

    if ! tmux has-session; then
        tmux new-session -s "Dots"
    else
        sessions=$(tmux list-sessions -F \#S)
        session=$(echo "${sessions}" | gum filter --placeholder "Pick session...")
        tmux switch-client -t "${session}" || tmux attach -t "${session}"
    fi
}

alias tl="tmux ls"
alias ta="tmux a"

function p() {
    local codedir="${HOME}/Code/"
    local sbdir="${codedir}Socialbrothers/"
    local result

    if [[ $# -ne 0 ]]; then
        result=$(zoxide query "${codedir}" "$@")
    else
        local basedir
        local selected

        case $(gum choose 'Work' 'Personal') in
            "Work") basedir="${sbdir}" ;;
            "Personal") basedir="${codedir}" ;;
            *) return ;;
        esac

        results=$(fd --type=d --prune --base-directory="${basedir}" --strip-cwd-prefix --path-separator='')
        selected="$(echo "${results}" | gum filter --height=20 --placeholder=Project... --indicator.foreground='#ff470b' --match.foreground='#ff470b')"

        result="${basedir}${selected}"
    fi

    if [[ -d ${result} ]]; then
        cd "${result}" || return
        open -g raycast://confetti
    fi
}

# Socialbrothers
function adbw() {
    wifion=$(adb shell settings get global wifi_on)
    if [[ ${wifion} == 1 ]]; then
        adb shell svc wifi disable
    else
        adb shell svc wifi enable
    fi
}

function lfcd() {
    tmp="$(mktemp)"
    lf -last-dir-path="${tmp}" "$@"
    if [[ -f ${tmp} ]]; then
        dir="$(cat "${tmp}")"
        rm -f "${tmp}"
        if [[ -d ${dir} ]]; then
            if [[ ${dir} != "${PWD}" ]]; then
                cd "${dir}" || exit
            fi
        fi
    fi
}
