return {
  kind = {
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Keyword = " ",
    Method = " ",
    Misc = " ",
    Module = " ",
    Operator = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  type = {
    Array = " ",
    Boolean = " ",
    Number = " ",
    Object = " ",
    String = " ",
  },
  documents = {
    File = " ",
    Files = " ",
    SymlinkFile = " ",
    Folder = " ",
    OpenFolder = " ",
    SymlinkFolder = " ",
  },
  git = {
    Add = " ",
    Diff = " ",
    Ignore = " ",
    Mod = " ",
    Remove = " ",
    Rename = " ",
    Untracked = " ",
    Repo = " ",
    Branch = " ",
  },
  ui = {
    BigCircle = " ",
    BigUnfilledCircle = " ",
    BookMark = " ",
    Bug = " ",
    Calendar = " ",
    Check = " ",
    ChevronRight = " ",
    Circle = " ",
    Close = " ",
    CloseAll = " ",
    Code = " ",
    Comment = " ",
    Create = " ",
    Dashboard = " ",
    Fire = " ",
    Gear = " ",
    History = " ",
    Lightbulb = " ",
    List = " ",
    Lock = " ",
    NewFile = " ",
    Note = " ",
    Package = " ",
    Pencil = " ",
    Project = " ",
    Search = " ",
    SearchCode = " ",
    SignIn = " ",
    SignOut = " ",
    Table = " ",
    Telescope = " ",
  },
  diagnostics = {
    Error = " ",
    Hint = " ",
    Information = " ",
    Question = " ",
    Warning = " ",
  },
  misc = {
    Robot = " ",
    Squirrel = " ",
    Tag = " ",
    Watch = " ",
  },
  arrows = {
    ChevronDown = " ",
    ChevronRight = " ",
    ChevronLeft = " ",
    ChevronUp = " ",
  },
}
