# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
format = "$all"
right_format = "$username$localip$time"

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"

[git_branch]
symbol = " "

[directory]
home_symbol = " "
repo_root_style = "cyan bold"
repo_root_format = " [$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[package]
display_private = true
symbol = " "

[ruby]
symbol = " "

[nodejs]
symbol = " "

[directory.substitutions]
"/" = " "
"Code" = " "
"Socialbrothers" = " "

[time]
disabled = false

[localip]
disabled = false
ssh_only = false

[username]
show_always = true
