---@type LazyPluginSpec[]
return {
  { "MunifTanjim/nui.nvim" },
  { "b0o/schemastore.nvim" },
  { "catppuccin/nvim", name = "catppuccin" },
  { "famiu/bufdelete.nvim" },
  { "j-hui/fidget.nvim" },
  { "nvimtools/none-ls.nvim" },
  { "karb94/neoscroll.nvim" },
  { "luukvbaal/stabilize.nvim" },
  { "mizlan/iswap.nvim" },
  { "moll/vim-bbye" },
  { "monaqa/dial.nvim" },
  { "neovim/nvim-lspconfig", dependencies = { "mason-lspconfig.nvim" } },
  { "nvim-lua/plenary.nvim" },
  { "tpope/vim-abolish" },
  { "mason-org/mason.nvim", version = "^1.0.0" },
  { "mason-org/mason-lspconfig.nvim", version = "^1.0.0" },
  { "justinsgithub/wezterm-types" },
}
