[colors]
foreground = "#abb2bf"
background = "#1E1E28"
cursor_bg = "#abb2bf"
cursor_border = "#abb2bf"
cursor_fg = "#1E1E28"
selection_bg = "#5c6370"
selection_fg = "#2c323c"

ansi = [
  "#282c34",
  "#e06c75",
  "#98c379",
  "#e5c07b",
  "#61afef",
  "#be5046",
  "#56b6c2",
  "#979eab",
]
brights = [
  "#393e48",
  "#d19a66",
  "#56b6c2",
  "#e5c07b",
  "#61afef",
  "#be5046",
  "#56b6c2",
  "#abb2bf",
]
