#:schema https://mise.jdx.dev/schema/mise.json

[tools]
"cargo:worktrunk" = "latest"
"github:code-yeongyu/go-claude-code-comment-checker" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:agent-browser" = "latest"
"npm:codemogger" = "latest"
"npm:eas-cli" = "latest"
"npm:fallow" = "latest"
"npm:kimaki" = "latest"
"npm:knip" = "latest"
"npm:neovim" = "latest"
"npm:ocx" = "latest"
"npm:opensrc" = "latest"
"npm:playwriter" = "latest"
"npm:poke" = "latest"
"npm:skills" = "latest"
"npm:taze" = "latest"
"npm:trash-cli" = "latest"
"npm:turbo" = "latest"
"npm:vercel" = "latest"
"npm:zele" = "latest"
bun = "latest"
codex = "latest"
graphite = "latest"
hcloud = "latest"
java = "25.0.3+9.0.LTS"
lazygit = "latest"
node = "24"
pitchfork = "latest"
pnpm = "10"
usage = "latest"
uv = "latest"

[settings]
experimental = true
trusted_config_paths = ["~/Code/"]
disable_backends = ["vfox"]
lockfile = true
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
package_manager = "bun"

[settings.cargo]
binstall = true

[settings.pipx]
uvx = true

[env]
'_'.path = "~/bin"
OPENCODE_EXPERIMENTAL = "1"
OPENCODE_EXPERIMENTAL_MARKDOWN = "1"
OPENCODE_EXPERIMENTAL_FILEWATCHER = "1"
OPENCODE_EXPERIMENTAL_SCOUT = "1"
OPENCODE_ENABLE_EXPERIMENTAL_MODELS = "1"
OPENCODE_EXPERIMENTAL_CUSTOMIZE_SKILL = "1"
OPENCODE_ENABLE_PARALLEL = "1"
CLAUDE_CODE_NO_FLICKER = true

OPENSPEC_NO_AUTO_CONFIG = "1"
OPENSPEC_NO_COMPLETIONS = "1"
