#:schema https://mise.jdx.dev/schema/mise.json

# Frequently used development tools on interactive workstations.
[tools]
"npm:agent-browser" = "latest"
"npm:knip" = "latest"
"npm:taze" = "latest"
"npm:turbo" = "latest"
