worktree-path = "{{ repo_path }}/../{{ repo }}.{{ branch | sanitize }}"

[post-create]
# cmux = "~/.config/worktrunk/hooks/cmux-create.sh {{ repo }} {{ branch }} {{ worktree_path }}"
graphite = "~/.config/worktrunk/hooks/graphite-create.sh {{ repo }} {{ branch }} {{ worktree_path }}"

[pre-remove]
# cmux = "~/.config/worktrunk/hooks/cmux-remove.sh {{ repo }} {{ branch }}"

[commit.generation]
command = "opencode run -m github-copilot/claude-haiku-4.5"

[list]
summary = true

[switch]
no-cd = true

[aliases]
gtc = "~/.config/worktrunk/hooks/graphite-step.sh c -a"
gtm = "~/.config/worktrunk/hooks/graphite-step.sh m -a"
gtls = "~/.config/worktrunk/hooks/graphite-step.sh ls"
gtss = "~/.config/worktrunk/hooks/graphite-step.sh ss"
gtsync = "~/.config/worktrunk/hooks/graphite-step.sh sync"
