#:schema https://pitchfork.jdx.dev/schema.json

[settings.general]
mise = true

[daemons.amp]
run = "exec amp --no-tui --runner-id MacBook-Pro-5 --remote-control-terminal --discover-dirs"
boot_start = true
retry = true
