#:schema https://pitchfork.jdx.dev/schema.json

[settings.general]
mise = true

[daemons.amp]
run = 'exec amp --no-tui --runner-id "$(hostname -s)" --remote-control-terminal'
dir = "~"
boot_start = true
retry = true
