# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

blocks:
    - alignment: left
      segments:
        - background: '#61AFEF'
          foreground: '#ffffff'
          powerline_symbol: 
          properties:
            style: folder
          style: powerline
          template: ' {{ .Path }} '
          templates_logic: join
          type: path
      type: prompt
final_space: true
version: 2

