require('globals')
require('plugins')
require('settings')
require('mappings')
require('colorscheme')
require('autocmds')
--require('lsp')

--require('plugins.lspinstall')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.galaxyline')
require('plugins.nvimtree')
require('plugins.whichkey')
--require('plugins.indentline')
require('plugins.gitsigns')
--require('plugins.compe')
require('plugins.lspsaga')
require('plugins.lspsignature')
require('plugins.lightbulb')
require('plugins.lspkind')
require('plugins.floaterm')
--require('plugins.shade')

--require('lsp.typescript')
--require('lsp.html')
--require('lsp.php')
--require('lsp.css')
--require('lsp.bash')
--require('lsp.emmet')

-- Autocommands
--vim.cmd('source ~/.config/nvim/vimscript/autocmds.vim')
vim.cmd('source ~/.config/nvim/vimscript/old.vim')
