require('plugins')
require('settings')
require('mappings')
require('colorscheme')
require('autocmds')
require('globals')
require('lsp')

require('plugins.telescope')
require('plugins.treesitter')
require('plugins.galaxyline')
require('plugins.nvimtree')
require('plugins.whichkey')
require('plugins.indentline')
require('plugins.gitsigns')
require('plugins.compe')
require('plugins.lspinstall')
require('plugins.lightbulb')
require('plugins.lspkind')

require('lsp.typescript')
require('lsp.html')

-- Autocommands
vim.cmd('source ~/.config/nvim/vimscript/autocmds.vim')
