# Inserts a blank line between shell prompts
add_newline = true
format = "$all$fill$shlvl$time$line_break$jobs$battery$status$shell$character"

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[](bold #8fe8a8)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[](bold #ff7ea3)"
vimcmd_symbol = "[](bold #7bc8fc)"

[git_branch]
symbol = " "

[git_commit]
tag_symbol = " "

[cmd_duration]
min_time = 0
show_milliseconds = true

[directory]
home_symbol = " "
repo_root_style = "cyan bold"
repo_root_format = " [$repo_root]($repo_root_style)[$before_root_path]($style)[$read_only]($read_only_style) "
truncate_to_repo = true

[package]
display_private = true
symbol = " "

[ruby]
symbol = " "

[nodejs]
symbol = " "

[php]
symbol = " "

[java]
symbol = " "
detect_folders = ["android"]
style = "red bold"

[rust]
symbol = " "

[python]
symbol = " "

[golang]
symbol = " "

[shlvl]
disabled = false
symbol = " "
threshold = 3
format = "[$symbol]($style)"

[directory.substitutions]
"/" = " "
"Code" = " "
"Socialbrothers" = " "

[time]
disabled = false
format = " [$time]($style)"

[localip]
disabled = false

[fill]
symbol = " "

[lua]
detect_files = [".lua-version", ".luarc.json", ".stylua.toml", ".luacheckrc"]
symbol = " "

[custom.next]
command = "pkgversion next"
when = "pkgversion next"
symbol = " "
format = "using [$symbol(v$output)]($style) "
description = "The current version of Next.js defined in the package.json"
style = "#ffffff bold"

[custom.react]
command = "jq '.dependencies.react?' -r -e package.json | sed 's/[^0-9\\.]//g'"
when = "jq '.dependencies.react?' -r -e package.json"
symbol = " "
format = "using [$symbol(v$output)]($style) "
description = "The current version of React defined in the package.json"
style = "blue bold"
